# Generated by Django 4.1.2 on 2022-10-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='head',
            field=models.CharField(default=-2017, max_length=100),
            preserve_default=False,
        ),
    ]
