# Generated by Django 4.1.2 on 2022-10-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_feature_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(default=-2024, max_length=500),
            preserve_default=False,
        ),
    ]
