# Generated by Django 4.1.7 on 2023-03-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='heading',
            new_name='head',
        ),
        migrations.AddField(
            model_name='feature',
            name='link',
            field=models.CharField(default=0.16666666666666666, max_length=700),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.CharField(max_length=10000),
        ),
    ]
